server:
  port: 8081
spring:
  data:
    mongodb:
      uri: ${DATA_SOURCE_URI}
      database: ${DATA_SOURCE_DBNAME}
      port: ${DATA_SOURCE_PORT}
    servlet:
      multipart:
        max-file-size: 256MB
        max-request-size: 256MB
        enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-name: Login com Google
            client-id: 853824473727-pct1egakt2dsui2cn8m5oc1n9efqdv9c.apps.googleusercontent.com
            client-secret: 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
            scopes:
              - openid
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/userinfo.email
            client-authentication-methods:
              - client_secret_basic
            authorization-grant-types:
              - authorization_code
              - refresh_token
              - client_credentials

          provider:
            google:
              user-name-attribute: email
              authorization-uri: http://localhost:8081/oauth2/token

config:
  uris:
    issuer-uri: ${ISSUER_URI}
    logout-uri: ${LOGOUT_URI}
    angular-uri: ${ANGULAR_URI}

logging:
  level:
    org:
      springframework:
        security:
          - TRACE
          - oauth2: TRACE